In [20]:
import numpy as np
import sys
import os

# Add project root to sys.path so 'src' is importable
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from src.data_pipeline.segmentation import segment_grid

grid = np.array([[1, 1, 0], [0, 2, 2]])
objects = segment_grid(grid)
print(objects[0]['color'])
print(objects[0]['size'])
print(objects[0]['bounding_box'])
print(objects[0]['pixel_mask'])


1
2
((np.int64(0), np.int64(0)), (np.int64(0), np.int64(1)))
[[1 1]]


In [21]:
from src.dsl.primitives import rotate90

grid = np.array([[1, 2], [3, 4]])
print(rotate90(grid))

[[2 4]
 [1 3]]


In [27]:
from src.data_pipeline.augmentation import  augment_demonstrations

demo_pairs = [(np.array([[1, 2], [3, 4]]), np.array([[4, 3], [2, 1]]))]
augmented = augment_demonstrations(demo_pairs)
print(len(augmented))

24


In [22]:
from src.dsl.primitives import rotate90, horizontal_mirror

inp = np.array([[1, 2], [3, 4]])
out = np.array([[3, 1], [4, 2]])

print(rotate90(inp))                # [[2 4], [1 3]]
print(horizontal_mirror(inp))       # [[2 1], [4 3]]
print(rotate90(horizontal_mirror(inp)))  # [[1 3], [2 4]]
print(horizontal_mirror(rotate90(inp)))  # [[4 2], [2 1]]

[[2 4]
 [1 3]]
[[2 1]
 [4 3]]
[[1 3]
 [2 4]]
[[4 2]
 [3 1]]


In [25]:
from src.symbolic_search.search import best_first_search
from src.symbolic_search.verifier import verify_program
from src.dsl.primitives import rotate90, horizontal_mirror

inp = np.array([[1, 2], [3, 4]])
out = horizontal_mirror(rotate90(inp))  # Compute the expected output

program, found = best_first_search([inp], [out], [rotate90, horizontal_mirror], 2, verify_program)
print(program)
print(found)

[<function rotate90 at 0x0000016DD62734C0>, <function horizontal_mirror at 0x0000016DE4BC9120>]
True
